name: Artifact Download

on:
  workflow_run:
    workflows: ["Java Build and Artifact Upload"]
    types:
      - completed  # Trigger only after the previous workflow completes successfully
  workflow_dispatch:  # Optional manual trigger

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      # Checkout the artefacts-store branch
      - name: Checkout artefacts-store branch
        uses: actions/checkout@v4
        with:
          ref: artefacts-store

      # Download the latest artifact from the triggering workflow run
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: demo-0.0.1-SNAPSHOT.jar       # Artifact name from the previous workflow
          path: artefacts/           # Folder where the artifact will be stored

      # List downloaded files for verification
      - name: List downloaded files
        run: ls -R artefacts/
