name: Docker Build and Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gurubeehyv/git_actions

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image with two tags
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.run_number }} .

      # Push Docker image to DockerHub
      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.run_number }}
