name: Java Build and Artifact Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    env:
      GIT_USER_NAME: bhuvanyuguru
      ARTIFACT_BRANCH: artefacts-store

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: target/*.jar

      - name: Push Artifacts to artefacts-store Branch
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git fetch origin ${{ env.ARTIFACT_BRANCH }}
          git checkout ${{ env.ARTIFACT_BRANCH }}
          mkdir -p artefacts
          cp target/*.jar artefacts/
          git add artefacts/
          git commit -m "Upload artifacts from run ${{ github.run_number }}" || echo "No changes to commit"
          git push origin ${{ env.ARTIFACT_BRANCH }}

      - name: Trigger Artifact Download Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: artifact-download.yml
          ref: main
