name: Java Build and Artifact Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  actions: write

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    env:
      GIT_USER_NAME: bhuvanyuguru
      ARTIFACT_BRANCH: artefacts-store

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Java project from demo folder
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./demo

      # Run tests from demo folder
      - name: Run Tests
        run: mvn test
        working-directory: ./demo

      # Upload build artifacts from demo/target/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: ./demo/target
          retention-days: 1

      # Push artifacts to another branch for persistence
      - name: Push Artifacts to artefacts-store Branch
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git fetch origin ${{ env.ARTIFACT_BRANCH }}
          git checkout ${{ env.ARTIFACT_BRANCH }}
          mkdir -p artefacts
          cp demo/target/*.jar artefacts/
          git add artefacts/
          git commit -m "Upload artifacts from run ${{ github.run_number }}" || echo "No changes to commit"
          git push origin ${{ env.ARTIFACT_BRANCH }}


      # Trigger the next pipeline
      # - name: Trigger Artifact Download Workflow
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: artifact-download.yml
      #     ref: main
      #     token: ${{ secrets.GITHUB_TOKEN }}
